# Generated by Django 5.2.1 on 2025-05-15 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('invite_code', models.CharField(max_length=10, unique=True)),
                ('clicked_users', models.ManyToManyField(blank=True, related_name='clicked_lessons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
